---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy list.weContextify.com
    steps:
      - uses: actions/checkout@v4

      - name: Set Name
        run: sed -i 's/name = "post2sheets"/name = "post2sheets-list.wecontextify.com"/g' wrangler.toml

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            TELEGRAM_ENABLED
            TELEGRAM_CHAT_ID
            GOOGLE_SHEET_ID
            GOOGLE_CLOUD_CREDENTIALS
            TELEGRAM_BOT_TOKEN
        env:
          TELEGRAM_ENABLED: 1
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
